version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/onlinequiz
      - JWT_SECRET=dev-secret-change
      - CORS_ORIGIN=http://localhost:8080
    depends_on:
      - mongo
volumes:
  mongo_data:

